version: "3.8"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile/api
      args:
        - "VENV_USER=csv2neo4j"
        - "VENV_PATH=/opt/csv2neo4j/venv"
      network: host
    network_mode: host
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI_FILE=/run/secrets/neo4j_uri
      - NEO4J_USER_FILE=/run/secrets/neo4j_user
      - NEO4J_PASSWORD_FILE=/run/secrets/neo4j_password
      - ELASTIC_URI_FILE=/run/secrets/elastic_uri
    secrets:
      - neo4j_uri
      - neo4j_user
      - neo4j_password
      - elastic_uri

  neo4j:
    build:
      context: .
      dockerfile: Dockerfile/neo4j
      network: host
    network_mode: host
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_connector_http_advertised__address=0.0.0.0:7474

  elastic:
    build:
      context: .
      dockerfile: Dockerfile/elasticsearch
      network: host
    network_mode: host
    ports:
      - "9200:9200"

secrets:
  neo4j_uri:
    file: secrets/neo4j_uri.txt
  neo4j_user:
    file: secrets/neo4j_user.txt
  neo4j_password:
    file: secrets/neo4j_password.txt
  elastic_uri:
    file: secrets/elastic_uri.txt
